add a Disconnecting event to MqttClient
dotnet/MQTTnet pull request #1964
Opened 2024-04-13 23:23 UTC by fazho

add a Disconnecting event to MqttClient

2024-04-14 05:21 UTC, fazho commented
@chkr1011 Could you please take a look?

2024-04-15 15:25 UTC, chkr1011 commented
What is the purpose of the new event? To me it looks like a copy of the already existing "Disconnected" event but it is fired before doing the actual disconnect!? Do you have a sample what it is used for?

2024-04-15 16:44 UTC, fazho commented
It's like the Connecting event, which happens right after the connection status is transitioned into Connecting but the work of connecting to the server has not started yet. 
Disconnected happens after everything is done, while Disconnecting happens before that. That is the difference.
With this new event, I can get an accurate reason code from the DISCONNECT packet when PublishAsync() errors out, because the DISCONNECTING event happens synchronously before all the resources of the client are released.
As a contrast, the Disconnected event happens afterwards, which means that the resources of the client are released first. And depending on the timing, PublishAsync() could error out before or after Disconnected event happens, in which I might not get the reason code when the error occurs.

Here is an example: https://github.com/dotnet/MQTTnet/issues/1963

2024-04-15 21:08 UTC, fazho commented
Basically it guarantees us the access to the reason code in the DISCONNECT packet when server disconnects the client and the client errors out.

2024-04-16 16:34 UTC, fazho commented
@chkr1011 could you let me know if my comments address your concern?

2024-04-18 16:12 UTC, fazho commented
@chkr1011 could you take another look?

2024-04-19 15:12 UTC, chkr1011 requested changes

2024-04-19 16:59 UTC, fazho commented on Source/MQTTnet/Client/MqttClient.cs
> +                await _events.DisconnectingEvent.InvokeAsync(new MqttClientDisconnectingEventArgs(
@chkr1011  good catch. Code updated.

2024-04-19 19:44 UTC, fazho commented
@chkr1011 Addressed your comments. Could you please take another look?

2024-04-20 10:22 UTC, chkr1011 commented
Thank you for your explanation. In my opinion there should be no new event at all because you have to change to do anything to avoid disconnecting etc. 

We might consider exposing the information in the Publish as well. Lets imagine the publish does not work and gets an error. We might add a property to the disconnection information so that you have it in the catch clause of the Publish method. Then you don't need to synchronize the data from one event handler to a field and access that field from a different event handler. That do you think about that?

2024-04-22 16:50 UTC, fazho commented
@chkr1011 that's even better. If I understand correctly, you are saying we should catch the exception from Publish, and re-throw a specific exception type (for example, MqttClientUnexpectedDisconnectReceivedException) that could contain the info from the disconnect packet.
There's only 1 problem I can think of - We are making a breaking change by re-throwing a new exception. In my example, when QoS is 0, what the client throws now, like TaskCanceledException or MqttCommunicationException, will be whatever the new exception we decide to throw to contain the disconnect info. Is that acceptable?
Meanwhile with this new event, we do not need to make any breaking changes.

2024-04-22 18:06 UTC, fazho commented
@chkr1011 I sent out another PR: https://github.com/dotnet/MQTTnet/pull/1974. Could you let me know if this meets your expectation?

2024-05-04 10:53 UTC, chkr1011 commented
@fazho Do we still need this feature? Am I wrong or is the pull request #1974 the solution for this?

2024-05-06 18:14 UTC, fazho commented
@chkr1011 No we don't need this PR given the new one: https://github.com/dotnet/MQTTnet/pull/1974

2024-05-06 18:15 UTC, closed without merging